### PR TITLE
Baseline GFE Fixes For Booting FreeBSD

### PR DESCRIPTION
**Pull request by jrtc27**
I am now able to build src_AWS_P2 for Verilator and load ELF files into the simulation. However, I cannot yet reproduce the simulation working; the ISA tests are seemingly correctly loaded, but execution hangs once the core is resumed at:

```
6061: TOP.mkXsimTop.top.lAWSP2_p2_core.core.debug_module.dm_run_control.dmcontrol_write: hart0 resume request
6292: D_MMU_Cache: cache size 8 KB, associativity 2, line size 64 bytes (= 8 XLEN words)
```

### CODE REVIEW

**Comment by joestoy** [comment]
@jrtc27: I see the same thing.  Looking at the vcd waves I see there are two reasons for the apparent hang (though actually for me the test I tried ran successfully to complettion).
(1) The tv trace seems to be getting dropped somewhere near the top level of hardware -- not sure why yet.
(2)  The connectal software for some reason reverses the order of fromhost and tohost.  So it expects the PASS/FAIL write to be to tohost, now at 0x10001008; but the test was writing to 0x10001000.

A revised version of link.ld to fix this (and to go in riscv-tests/env/p) is appended

joe

============================
OUTPUT_ARCH( "riscv" )
ENTRY(_start)

tohost = 0x10001008;

SECTIONS
{
  . = 0xC0000000;
  .text.init : { *(.text.init); . = ALIGN(0x1000); } = 0xaa
  . = ALIGN(0x1000);
  .text : { *(.text); . = ALIGN(0x1000); } = 0xaa
  . = ALIGN(0x1000);
  .data : { *(.data); . = ALIGN(0x1000); } = 0xaa
  . = ALIGN(8);
  _bss_begin = .;
  .bss : { *(.bss) }
  . = ALIGN(8);
  _end = .;
}

**Comment by jrtc27** [comment]
@joestoy Thanks, in the meantime I had managed to get a verbose Flute build and saw that it was writing 1 to its tohost and therefore passing. The ISA tests I was running were storing that to uncached "DRAM" (in simulation), which it seems the current harness does not intercept.

**Comment by jrtc27** [comment]
I have pushed two commits which I believe make the htif/tohost/fromhost handling much saner. The order is corrected to the standard one, and .tohost/.fromhost can also be independent (rather than before, where .tohost was treated as implying .htif).

**Comment by jrtc27** [comment]
VirtIO doesn't yet want to play ball despite my attempts at fixing it. If I remove the devices from the device tree, my mfsroot GFE bbl+kernel (the bbl-riscv64.GFE I provided on Friday) boots to a working shell prompt:

```
CONSOLE: # uname -a
uname -a

CONSOLE: FreeBSD  13.0-CURRENT FreeBSD 13.0-CURRENT #0 8dd336ee478b-c325010(dev): Fri May  1 17:13:04 BST 2020     jrtc4@zeno.sec.cl.cam.ac.uk:/home/jrtc4/cheri/build/cheribsd-riscv64-build/home/jrtc4/cheri/cheribsd/riscv.riscv64/sys/GFE  riscv
```

**Review by jameyhicks — APPROVED** [review]
Looks good. Thank you for the pull request.

**Comment by jameyhicks** [comment]
Rebased and merged manually due to conflicting file.

**Comment by jrtc27** [comment]
https://github.com/acceleratedtech/ssith-aws-fpga/commit/62b8d177fce03371d1fb8c8066e688b94d7dc301 has a merge conflict still in it.

**Comment by joestoy** [comment]
> I have pushed two commits which I believe make the htif/tohost/fromhost handling much saner. The order is corrected to the standard one, and .tohost/.fromhost can also be independent (rather than before, where .tohost was treated as implying .htif).

@jrtc27 @jameyhicks:These changes are good; but now we need to decide where tohost/fromhost are to be.  Currently they're still around 10001000, and the clint has been put back there overlapping them.  So any PASS/FAIL reports from ISA tests don't make it to the host, but  are  sent to (and rejected by) the clint.

**Pull request closed without merging**
